spring.application.name=event-api
spring.servlet.multipart.max-file-size=2MB
spring.servlet.multipart.max-request-size=2MB
server.port=${PORT:8080}

# Health check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Rabbit Mq
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.username=${RABBIT_USERNAME:rabbitmq}
spring.rabbitmq.password=${RABBIT_PASSWORD:rabbitmq}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.virtual-host=${RABBIT_VHOST:/}
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# RABBITMQ Create Event
rabbitmq.exchange.create.name=events.v2.create-event
rabbitmq.exchange.error.create.name=events.v2.create-error-event
rabbitmq.create.error.queue.name=events.v2.create-event-queue.error

# RABBITMQ Get Event
rabbitmq.exchange.get-all.name=events.v2.get-all-event

# RABBITMQ Get Event
rabbitmq.exchange.update.name=events.v2.update-event

# RABBITMQ Processor Delete Event
rabbitmq.exchange.delete.name=events.v2.delete-processor

# RABBITMQ Notification Event
rabbitmq.exchange.error.create.notification.name=events.v2.create-error-notification

# RABBITMQ Processor Create Sale Event
rabbitmq.exchange.sale.create.name=events.v2.create-sale-processor

# RABBITMQ Processor Update Sale Event
rabbitmq.exchange.sale.update.name=events.v2.update-sale-processor

# RABBITMQ Processor Delete Sale Event
rabbitmq.exchange.sale.delete.name=events.v2.delete-sale-processor

# AWS S3
aws.access_key_id=${ACCESS_KEY_ID}
aws.secret_access_key=${SECRET_ACCESS_KEY}
s3.bucket=${S3_BUCKET}
s3.region=${S3_REGION}

# Security
security.jwt.secret=${JWT_SECRET}

# MONGO DB
spring.data.mongodb.uri=${SPRING_DATA_MONGODB_URI:mongodb://admin:123456@localhost:27017/event_api?authSource=admin}
# Client
organization.api.url.base=${ORGANIZATION_API_URL_BASE:http://localhost:8081}
organization.api.endpoint=${ORGANIZATION_API_URL_ENDPOINT:/api/v1/organizacao/unit/}

