services:
  event-mongo-db:
    image: mongo:latest
    container_name: event-mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/lib/rabbitmq

  postgres:
    image: postgres:15.7
    restart: unless-stopped
    container_name: postgres-15.7
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: eventos_api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data: