services:
  event-mongo-db:
    image: mongo:latest
    container_name: event-mongo-db
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=123456
    ports:
      - 27017:27017
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5

  rabbitmq:
    image: rabbitmq:3.10.5-management
    container_name: rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: 'rabbitmq'
      RABBITMQ_DEFAULT_PASS: 'rabbitmq'
    ports:
      - '15672:15672'
      - '5672:5672'
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
      - rabbitmq_log:/var/lib/rabbitmq/log
    healthcheck:
      test: ["CMD", "rabbitmq-diagnostics", "-q", "check_running"]
      interval: 10s
      timeout: 5s
      retries: 5

  postgres:
    image: postgres:15.7
    restart: unless-stopped
    container_name: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./docker/postgres/init:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d postgres"]
      interval: 10s
      timeout: 5s
      retries: 5

  event_api:
    build:
      context: ./event-api
      dockerfile: Dockerfile
    container_name: event_api
    ports:
      - "8080:8080"
    env_file:
      - ./event-api/variaveis.env
    depends_on:
      event-mongo-db:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: rabbitmq
      RABBIT_PASSWORD: rabbitmq
      MONGO_USER: admin
      MONGO_PASS: 123456
      MONGO_HOST: event-mongo-db
      MONGO_DB: admin

  processor_api:
    build:
      context: ./processor_api
      dockerfile: Dockerfile
    container_name: processor_api
    depends_on:
      postgres:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: rabbitmq
      RABBIT_PASSWORD: rabbitmq
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: eventos_api
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

  notification_api:
    build:
      context: ./notification-api
      dockerfile: Dockerfile
    container_name: notification_api
    depends_on:
      rabbitmq:
        condition: service_healthy
    environment:
      RABBIT_HOST: rabbitmq
      RABBIT_PORT: 5672
      RABBIT_USERNAME: rabbitmq
      RABBIT_PASSWORD: rabbitmq
      JAVA_OPTS: >-
        --add-opens java.base/java.time.chrono=ALL-UNNAMED
        --add-opens java.base/java.time.format=ALL-UNNAMED
        --add-opens java.base/java.time.temporal=ALL-UNNAMED
        --add-opens java.base/java.time.zone=ALL-UNNAMED

  organization_api:
    build:
      context: ./organization_api
      dockerfile: Dockerfile
    container_name: organization_api
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_healthy
    environment:
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: organization_api
      DB_USERNAME: postgres
      DB_PASSWORD: postgres

volumes:
  rabbitmq_data:
  rabbitmq_log:
  postgres_data:
