spring.application.name=notification

# Rabbit Mq
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

rabbitmq.exchange.error.create.notification.name=events.v1.create-error-notification
rabbitmq.queue.error.create.notification.name=events.v1.create-error-notification-queue
