spring.application.name=notification

# Rabbit Mq
spring.rabbitmq.host=localhost
spring.rabbitmq.username=rabbitmq
spring.rabbitmq.password=rabbitmq
spring.rabbitmq.port=5672

# Rabbit Mq Create
rabbitmq.exchange.create-notification.name=events.v1.create-notification-event
rabbitmq.queue.create-notification.name=events.v1.queue.create-notification-event

# Rabbit Mq Get
rabbitmq.exchange.get-all-notification.name=events.v1.get-all-notification-event
rabbitmq.queue.get-all-notification.name=events.v1.queue.get-all-notification-event

# Rabbit Mq Update
rabbitmq.exchange.update-notification.name=events.v1.update-notification-event
rabbitmq.queue.update-notification.name=events.v1.queue.update-notification-event

# Rabbit Mq Error
rabbitmq.exchange.error.create.notification.name=events.v1.create-error-notification
rabbitmq.queue.error.create.notification.name=events.v1.create-error-notification-queue
rabbitmq.exchange.update-error-notification.name=events.v1.update-error-notification-event
rabbitmq.queue.update-error-notification.name=events.v1.queue.update-error-notification-event
