spring.application.name=processor_api
server.port=8181

# DATA SOURCE
spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:eventos_api}
spring.datasource.driver-class-name=org.postgresql.Driver
spring.datasource.username=${DB_USERNAME:postgres}
spring.datasource.password=${DB_PASSWORD:postgres}

# JPA/HIBERNATE
spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update

# RABBITMQ
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.username=${RABBIT_USERNAME:rabbitmq}
spring.rabbitmq.password=${RABBIT_PASSWORD:rabbitmq}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.virtual-host=${RABBIT_VHOST:/}
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# RABBITMQ Create Event
rabbitmq.exchange.create.name=events.v2.create-event
rabbitmq.create.queue.name=events.v2.create-queue-event.save-database
rabbitmq.exchange.error.create.name=events.v2.create-error-event

# RABBITMQ Get Event
rabbitmq.exchange.get-all.name=events.v2.get-all-event
rabbitmq.get-all.queue.name=events.v2.get-all-queue-event


# RABBITMQ Update Event
rabbitmq.exchange.update.name=events.v2.update-event
rabbitmq.update.queue.name=events.v2.update-queue-event

# RABBITMQ Delete Event
rabbitmq.exchange.delete.name=events.v2.delete-processor
rabbitmq.delete.queue.name=events.v2.delete-queue-event

# RABBITMQ Create Sale Event
rabbitmq.exchange.sale.create.name=events.v2.create-sale-processor
rabbitmq.sale.create.queue.name=events.v2.create-queue-sale

# RABBITMQ Update Sale Event
rabbitmq.exchange.sale.update.name=events.v2.update-sale-processor
rabbitmq.sale.update.queue.name=events.v2.update-queue-sale

# RABBITMQ Processor Delete Sale Event
rabbitmq.exchange.sale.delete.name=events.v2.delete-sale-processor
rabbitmq.sale.delete.queue.name=events.v2.delete-queue-sale

# RABBITMQ Processor Reservation Sale Event
rabbitmq.exchange.sale.create-reservation-processor.name=events.v2.create-reservation-processor-sale
rabbitmq.queue.sale.create-reservation-processor.name=events.v2.create-reservation-queue-processor-sale
rabbitmq.exchange.sale.create-reservation.name=events.v2.create-reservation-sale

# RABBITMQ Notification Event
rabbitmq.exchange.create-notification.name=events.v2.create-notification-event
rabbitmq.exchange.get-all-notification.name=events.v2.get-all-notification-event
rabbitmq.exchange.update-notification.name=events.v2.update-notification-event
rabbitmq.exchange.delete-notification.name=events.v2.delete-notification-event
rabbitmq.exchange.update-error-notification.name=events.v2.update-error-notification-event

# RABBITMQ Notification Event Sale
rabbitmq.exchange.sale.create-notification.name=events.v2.create-notification-sale
rabbitmq.exchange.sale.update-notification.name=events.v2.update-notification-sale
rabbitmq.exchange.sale.delete-notification.name=events.v2.delete-notification-sale
