spring.application.name=notification
server.port=${PORT:8084}
spring.main.web-application-type=servlet

# Health check
management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

# Firebase
firebase.config=${FIREBASE_CONFIG}

# Rabbit Mq
spring.rabbitmq.host=${RABBIT_HOST:localhost}
spring.rabbitmq.username=${RABBIT_USERNAME:rabbitmq}
spring.rabbitmq.password=${RABBIT_PASSWORD:rabbitmq}
spring.rabbitmq.port=${RABBIT_PORT:5672}
spring.rabbitmq.virtual-host=${RABBIT_VHOST:/}
spring.rabbitmq.listener.simple.default-requeue-rejected=false

# Rabbit Mq Create Event
rabbitmq.exchange.create-notification.name=events.v2.create-notification-event
rabbitmq.queue.create-notification.name=events.v2.queue.create-notification-event

# Rabbit Mq Get Event
rabbitmq.exchange.get-all-notification.name=events.v2.get-all-notification-event
rabbitmq.queue.get-all-notification.name=events.v2.queue.get-all-notification-event

# Rabbit Mq Update Event
rabbitmq.exchange.update-notification.name=events.v2.update-notification-event
rabbitmq.queue.update-notification.name=events.v2.queue.update-notification-event

# Rabbit Mq Delete Event
rabbitmq.exchange.delete-notification.name=events.v2.delete-notification-event
rabbitmq.queue.delete-notification.name=events.v2.queue.delete-notification-event

# Rabbit Mq Error Event
rabbitmq.exchange.error.create.notification.name=events.v2.create-error-notification
rabbitmq.queue.error.create.notification.name=events.v2.create-error-notification-queue
rabbitmq.exchange.update-error-notification.name=events.v2.update-error-notification-event
rabbitmq.queue.update-error-notification.name=events.v2.queue.update-error-notification-event

# Rabbit Mq Create Event Sale
rabbitmq.exchange.sale.create-notification.name=events.v2.create-notification-sale
rabbitmq.queue.sale.create-notification.name=events.v2.queue.create-notification-sale

# Rabbit Mq Update Event
rabbitmq.exchange.sale.update-notification.name=events.v2.update-notification-sale
rabbitmq.queue.sale.update-notification.name=events.v2.queue.update-notification-sale

# Rabbit Mq Delete Event Sale
rabbitmq.exchange.sale.delete-notification.name=events.v2.delete-notification-sale
rabbitmq.queue.sale.delete-notification.name=events.v2.queue.delete-notification-sale